### ISSUE TITLE
better use "--word-diff=porcelain"

### ISSUE THREAD

**Issue by jnavila** [jduckles/pwdiff#3]
This makes the output more machine readable

**Comment by jduckles** [comment]
Hmmm interesting, I don't think this flag was there when I first built this. I'd welcome a PR with an implementation of this, but for me the current implementation is simple enough to be quite useful. 

Am I correct in understanding that `--word-diff=porcelain` would only help in the edge cases where the content of the original text has the strings `[- -] {+ +}`?
